$font = Sans-serif

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $HOME/Pictures/wallpaper
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(255, 255, 255)
    check_color = rgb(143, 143, 143)
    fail_color = rgb(255, 180, 180)

    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Password
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font

    position = -30, -100
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -250
    halign = center
    valign = top
}

label {
    monitor =
    text = $LAYOUT[en,ru]
    font_size = 16
    onclick = hyprctl switchxkblayout all next

    position = 225, -20
    halign = center
    valign = center
}
